baseURL = "http://localhost"
relativeURLs = true

copyright = ""
title = "Whodunnit"
#paginate = 10
enableRobotsTXT = true
# Enable to calculate the last modified date from Git history and show it in the post header
#enableGitInfo = true

[build]
  noJSConfigInAssets = true
  _merge = "deep"
  [build.buildStats]
    # With each build, Hugo writes a hugo_stats.json file that contains arrays
    # of the class attributes, id attributes, and tags of each HTML element 
    # within the published site. For production builds, this file is required 
    # by PurgeCSS to prune unused CSS.
    enable = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This setting allows inlining <script> and <style> tags in markdown, 
      # which is useful and required to use Prism plugins, but may be dangerous 
      # if the content isn't trustworthy.
      unsafe = true

[imaging]
  # JPEG and WebP image processing quality, defaults to 75%
  #quality = 75

[outputs]
  home = ["html", "rss", "searchIndex"]

[outputFormats]
  [outputFormats.searchIndex]
    mediaType = "application/json"
    baseName = "search-index"
    isPlainText = true
    notAlternative = true

[params]
  # dark or light, defaults to light. Local storage and OS preference override this param. For more details see: 
  # https://github.com/schnerring/hugo-theme-gruvbox/issues/34#issuecomment-1235870375
  #defaultTheme = "light"
  # gray red green yellow blue purple aqua orange, defaults to blue
  themeColor = "purple"
  # soft medium hard, defaults to medium
  #themeContrast = "medium"

  [params.logo]
    text = "whodunnit"
    url = "/"

  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "bash",
      "diff",
      "toml"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "line-numbers",
      "command-line",
      "diff-highlight"
    ]
  
  # By default, the theme creates resized versions of images ranging from 300 to
  # 700 pixels wide in increments of 200 pixels
  #[params.imageResize]
  #  min = 300
  #  max = 700
  #  increment = 200
  
  [params.tagCloud]
    enable = false
    minFontSizeRem = 0.8
    maxFontSizeRem = 2.0

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 30

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
  [languages.de]
    languageName = "Deutsch"
    weight = 20

[module]
  [[module.mounts]]
    source = "node_modules/prismjs"
    target = "assets/prismjs"
  [[module.mounts]]
    source = "node_modules/prism-themes/themes"
    target = "assets/prism-themes"
